resources:
  repositories:
  - repository: pre-commit-hooks
    type: github
    ref: refs/heads/main
    name: thomast1906/tamops-pre-commit-hooks
    endpoint: 'thomast1906'

stages:
  - stage: stage1
    jobs:
    - job: stage1job
      steps:
        - checkout: self
        - checkout: pre-commit-hooks
        - script: ls $(Agent.BuildDirectory)
        - task: ShellScript@2
          inputs:
            scriptPath: $(Agent.BuildDirectory)/pre-commit-hooks/app_gateway_backend_checks.sh
        # - task: Bash@3
        #   inputs:
        #       targetType: 'filePath'
        #       filePath: $(Agent.BuildDirectory)/pre-commit-hooks/app_gateway_backend_checks.sh'
        #       failOnStderr: true
        # - template: tamops-pre-commit-hooks/pre-commit-hooks/app_gateway_backend_checks.sh@pre-commit-hooks
