resources:
  repositories:
  - repository: pre-commit-hooks
    type: github
    ref: refs/heads/main
    name: thomast1906/tamops-pre-commit-hooks
    endpoint: 'thomast1906'

stages:
  - stage: stage1
    jobs:
    - job: stage1job
      steps:
        # - checkout: pre-commit-hooks
        # - script: ls
        # - task: Bash@3
        #   inputs:
        #       targetType: 'filePath'
        #       filePath: tamops-pre-commit-hooks/pre-commit-hooks/app_gateway_backend_checks.sh@pre-commit-hooks
        #       failOnStderr: true
        - template: tamops-pre-commit-hooks/pre-commit-hooks/app_gateway_backend_checks.sh@pre-commit-hooks
