name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - name: Setup Script
        run: |
          chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
      - name: Setup Terraform
        run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
        working-directory: ./
        shell: bash

      - uses: actions/setup-python@v3
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.26.1

      - uses: pre-commit/action@v3.0.0
        with: 
          extra_args: terraform_fmt --all-files
        continue-on-error: true

      # - uses: stefanzweifel/git-auto-commit-action@v3
      #   with:
      #     file_pattern: example.txt *.tf *.tfvars
      #     commit_message: 'Auto Pushed robot'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '-u'
          add_options: '--ignore-errors'

